# Config file for automatic testing at travis-ci.com

language: python

jobs:
  include:
    - python: 3.6
      env: TOXENV=python3.6
    - python: 3.7
      env: TOXENV=python3.7
    - python: 3.8
      env: TOXENV=python3.8
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=flake8
    - env: CONDA_BLD_PATH=~/conda-bld
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install conda-build anaconda-client
        - conda config --set anaconda_upload no
      script:
        - conda build -c conda-forge ci/conda_recipe
      after_success:
        - chmod +x ci/conda_recipe/conda_upload.sh

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

deploy:
  # Assuming you have installed the travis-ci CLI tool, after you
  # create the Github repo and add it to Travis, run the
  # following command to finish PyPI deployment setup:
  # $ travis encrypt --add deploy.password
  # Paste the hashed password in the `secure` field
  - provider: pypi
    distributions: sdist bdist_wheel
    username: phausamann
    password:
      secure: "MV9CQO/OC6y2Rz9E+N17l8pVcC8uMn8h4LtQL5nDXbW6h0oUk4PnPFYSztlrKbUkrgtptc8q4wcSpnoAf8afJAQUBEKnCVNGXG0/452HHev8c7aIAG0vqt7IvLWbFKUb7b3B7OsTYc4O8atu7s4WAILdQ+bLa38e8jqmCnLS1y+o06LbGyT9Xqu3bIIUp5TEEl5YO2vHpG20qjvV/BYKP4YUrW0UOY6Q2E2yAvltzKbrRD6Co2dE+vLAmZF1cBZo7TBPW6gRYmlLAlHVEYdUnqQKzeggYqVugZ1j/H4eKk2h3mTQX7cjXEj0ozCdmYGYvLQf3i4Y60eUnfkIXJEbqn8daoiXcRGfa2ismsF5h3lv15IkciUO5w4fyZ7bHC51mumqlMr/LufHusHLYivaZ3xIcGZJ4R4TLtxhGkuUshQspWVi4pkLl6YExQ9vswtb080JFJuT8xtuh+RTz45l2ujqaWnhjdISHVG66+rMcqzKsS9QxT7WDXaOCf9ZqxBD4Hkf4WdaXZSn6ppHZxro5m09vFAzSptARD0O6TpLzXRoTG+pVTB2ftG0//EJ4W0RuYao9Gnmk+asHIdtpQd57RCXxWP8wO1kPOKIVhniivuXBreuzYYDvhs5WhZy1SZISwCrVIDdXszNEUKncRof1xQjWA9IBmFsVIav9IeUPrg="
    on:
      tags: true
      repo: phausamann/xrview
      python: 3.7
    skip_cleanup: true
  # Install anaconda client, then run:
  # $ anaconda auth -c -n travis --url https://anaconda.org/<username> --scopes "api:write api:read"
  # and add the generated token as $ANACONDA_TOKEN to the repo's env variables
  # on travis
  - provider: script
    script: ci/conda_recipe/conda_upload.sh
    on:
      tags: true
      repo: phausamann/xrview
      condition: "$CONDA_BLD_PATH = $HOME/conda-bld"
    skip_cleanup: true
