name: xrview
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  # scientific
  - numpy
  - pandas
  - xarray
  - scipy
  # plotting
  - bokeh
  - tornado
  - notebook
  - requests
  - firefox
  - geckodriver
  - selenium
  # testing
  - pytest
  - pytest-runner
  - pytest-cov
  - nbval
  - coverage
  - flake8
  - tox
  - bump2version
  # documentation
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
