name: xrview
channels:
  - conda-forge
dependencies:
  - python=3.6.6
  - pip=19.1.1
  # scientific
  - numpy=1.16.3
  - pandas=0.24.2
  - xarray=0.12.1
  - scipy=1.2.0
  # plotting
  - bokeh=1.1.0
  - tornado=4.5.3
  - selenium=3.141.0
  - phantomjs=2.1.1
  - notebook=5.7.8
  - requests=2.22.0
  - pygments=2.4.0
# - svgutils=0.3.1
  # testing
  - pytest=4.5.0
  - pytest-runner=4.4
  - coverage=4.5.3
  - flake8=3.5.0
  - tox=3.5.2
  - bumpversion=0.5.3
  - twine=1.12.1
  # documentation
  - sphinx=2.0.1
  - sphinx_rtd_theme=0.4.3
  - numpydoc=0.9.1
