name: xrview
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  # scientific
  - numpy
  - pandas
  - xarray
  - scipy
  # plotting
  - bokeh>=2.2
  - tornado
  - notebook
  - requests
  - firefox
  - geckodriver
  - selenium
  # testing
  - pytest
  - pytest-runner
  - pytest-cov
  - nbval
  - coverage
  # documentation
  - sphinx=3.2.1
  - sphinx_rtd_theme=0.5.0
  - numpydoc=1.1.0
