name: xrview
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - pip=19.1.1
  - numpy=1.16.3
  - pandas=0.24.2
  - xarray=0.12.1
  - bokeh=1.1.0
  - tornado=4.5.3
  - scipy=1.2.0
  - notebook=5.7.8
  - svgutils=0.3.1
  - requests=2.22.0
  - pygments=2.4.0
  - pytest=4.5.0
  - pytest-runner=4.4
  - sphinx=2.0.1
  - sphinx_rtd_theme=0.4.3
  - coverage=4.5.3
  - bumpversion=0.5.3
  - flake8=3.5.0
  - tox=3.5.2
  - twine=1.12.1
